"""Deterministic registry export helpers for Aegis OS."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

from .asset_resolver import AssetResolver
from .models import Asset

EXPORT_SECTIONS = ("assets", "domains", "tags", "releases")
_CATALOG_PREFIXES = ("domain.", "tag.", "release.")


def build_registry_export(
    resolver: AssetResolver,
    repo_root: Path,
    sections: Iterable[str],
) -> dict[str, Any]:
    """Build a JSON-compatible, deterministic registry export payload."""

    selected = tuple(dict.fromkeys(sections))
    payload_sections: dict[str, list[dict[str, Any]]] = {}

    for section in selected:
        payload_sections[section] = [
            _asset_to_dict(asset, repo_root)
            for asset in _assets_for_section(resolver, section)
        ]

    return {
        "schema_version": "1.0",
        "export": "aegis-registry",
        "sections": payload_sections,
        "counts": {
            section: len(items)
            for section, items in payload_sections.items()
        },
    }


def render_registry_export(payload: dict[str, Any], output_format: str) -> str:
    """Render an export payload as JSON or Markdown."""

    if output_format == "json":
        return json.dumps(
            payload,
            indent=2,
            ensure_ascii=False,
            sort_keys=True,
        ) + "\n"
    if output_format == "markdown":
        return _render_markdown(payload)
    raise ValueError(f"Unsupported export format: {output_format}")


def write_export(
    repo_root: Path,
    output_path: Path,
    content: str,
    *,
    force: bool,
) -> Path:
    """Write export content, refusing accidental overwrites by default."""

    destination = (
        output_path.resolve()
        if output_path.is_absolute()
        else (repo_root / output_path).resolve()
    )

    if destination.exists() and not force:
        raise FileExistsError(
            f"Refusing to overwrite existing export: {destination}. "
            "Pass --force after reviewing it."
        )
    if destination.exists() and destination.is_dir():
        raise IsADirectoryError(f"Export destination is a directory: {destination}")

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")
    return destination


def _assets_for_section(resolver: AssetResolver, section: str) -> list[Asset]:
    if section == "assets":
        matches = (
            asset
            for asset in resolver.assets
            if not asset.id.startswith(_CATALOG_PREFIXES)
        )
    else:
        prefix = {
            "domains": "domain.",
            "tags": "tag.",
            "releases": "release.",
        }.get(section)
        if prefix is None:
            raise ValueError(f"Unsupported export section: {section}")
        matches = (asset for asset in resolver.assets if asset.id.startswith(prefix))

    return sorted(matches, key=lambda asset: asset.id)


def _asset_to_dict(asset: Asset, repo_root: Path) -> dict[str, Any]:
    source_file = ""
    if asset.source_file:
        try:
            source_file = str(asset.source_file.relative_to(repo_root))
        except ValueError:
            source_file = str(asset.source_file)

    return {
        "id": asset.id,
        "name": asset.name,
        "type": asset.type,
        "domain": asset.domain,
        "path": asset.path,
        "tags": list(asset.tags),
        "related_assets": list(asset.related_assets),
        "source_file": source_file,
        "metadata": dict(asset.metadata),
    }


def _render_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# Aegis OS Registry Export",
        "",
        "This file is a deterministic registry export generated by Aegis OS.",
    ]

    sections: dict[str, list[dict[str, Any]]] = payload["sections"]
    for section, items in sections.items():
        lines.extend(["", f"## {section.title()} ({len(items)})", ""])
        lines.extend(_render_section(section, items))

    return "\n".join(lines) + "\n"


def _render_section(section: str, items: list[dict[str, Any]]) -> list[str]:
    if not items:
        return ["No entries."]

    if section == "assets":
        lines = [
            "| ID | Name | Type | Domain | Tags | Path |",
            "|---|---|---|---|---|---|",
        ]
        for item in items:
            lines.append(
                "| "
                + " | ".join(
                    [
                        _cell(item["id"]),
                        _cell(item["name"]),
                        _cell(item["type"]),
                        _cell(item["domain"]),
                        _cell(", ".join(item["tags"])),
                        _cell(item["path"]),
                    ]
                )
                + " |"
            )
        return lines

    columns = {
        "domains": ("ID", "Name", "Owner", "Status"),
        "tags": ("ID", "Name", "Category", "Description"),
        "releases": ("ID", "Name", "Version", "Status", "Maturity"),
    }[section]
    metadata_keys = {
        "domains": ("owner", "status"),
        "tags": ("category", "description"),
        "releases": ("version", "status", "maturity"),
    }[section]
    lines = [
        "| " + " | ".join(columns) + " |",
        "|" + "|".join("---" for _ in columns) + "|",
    ]
    for item in items:
        values = [item["id"], item["name"]]
        values.extend(item["metadata"].get(key, "") for key in metadata_keys)
        lines.append("| " + " | ".join(_cell(value) for value in values) + " |")
    return lines


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ") or "-"
