"""Markdown registry report generation for Aegis OS."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .asset_resolver import AssetResolver
from .models import Asset

REPORTS_SUBDIR = Path("reports") / "registry"


@dataclass(slots=True)
class GeneratedReport:
    """A single generated report file."""

    name: str
    path: Path

    def to_dict(self) -> dict[str, str]:
        return {"name": self.name, "path": str(self.path)}


def _relative_path(repo_root: Path, path: str) -> str:
    """Best-effort relative path, kept as-is if it can't be resolved."""

    if not path:
        return ""
    try:
        return str((repo_root / path).resolve().relative_to(repo_root))
    except (OSError, ValueError):
        return path


def generate_registry_summary(
    resolver: AssetResolver,
    repo_root: Path,
    registry_files: list[Path],
) -> str:
    """Build REGISTRY_SUMMARY.md content."""

    lines: list[str] = [
        "# Aegis OS - Registry Summary",
        "",
        "Generated by:",
        "",
        "```text",
        "aegis report generate registry-summary",
        "```",
        "",
        "## Summary",
        "",
        "| Registry File | Entry Count |",
        "|---|---:|",
    ]

    counts: dict[Path, int] = {file: 0 for file in registry_files}
    for asset in resolver.assets:
        if asset.source_file in counts:
            counts[asset.source_file] += 1

    for file in sorted(registry_files):
        rel = file.relative_to(repo_root)
        lines.append(f"| `{rel}` | {counts.get(file, 0)} |")

    lines += [
        "",
        "## Totals",
        "",
        "```text",
        f"Registry files: {len(registry_files)}",
        f"Total entries: {len(resolver.assets)}",
        "```",
        "",
        "## Final Principle",
        "",
        "> Registry summaries make the Aegis OS asset catalog easier to inspect.",
    ]
    return "\n".join(lines) + "\n"


def generate_asset_map(resolver: AssetResolver, repo_root: Path) -> str:
    """Build ASSET_MAP.md content."""

    lines: list[str] = [
        "# Aegis OS - Asset Map",
        "",
        "Generated by:",
        "",
        "```text",
        "aegis report generate asset-map",
        "```",
        "",
        "## Assets",
        "",
        "| ID | Name | Type | Domain | Path |",
        "|---|---|---|---|---|",
    ]

    for asset in sorted(resolver.assets, key=lambda a: (a.domain, a.id)):
        path = _relative_path(repo_root, asset.path)
        lines.append(
            f"| `{asset.id}` | {asset.name} | {asset.type} | "
            f"{asset.domain} | `{path}` |"
        )

    lines += [
        "",
        "## Totals",
        "",
        "```text",
        f"Total assets: {len(resolver.assets)}",
        "```",
        "",
        "## Final Principle",
        "",
        "> Asset maps make registered Aegis OS assets easier to inspect and navigate.",
    ]
    return "\n".join(lines) + "\n"


def generate_domain_report(resolver: AssetResolver, repo_root: Path) -> str:
    """Build DOMAIN_REPORT.md content."""

    by_domain: dict[str, list[Asset]] = {}
    for asset in resolver.assets:
        if not asset.domain:
            continue
        by_domain.setdefault(asset.domain, []).append(asset)

    domains = sorted(by_domain)

    lines: list[str] = [
        "# Aegis OS - Domain Report",
        "",
        "Generated by:",
        "",
        "```text",
        "aegis report generate domain-report",
        "```",
        "",
        "## Summary",
        "",
        "| Domain | Asset Count |",
        "|---|---:|",
    ]

    for domain in domains:
        lines.append(f"| {domain} | {len(by_domain[domain])} |")

    lines += ["", "## Assets by Domain"]

    for domain in domains:
        lines += [
            "",
            f"### {domain}",
            "",
            "| ID | Name | Type | Path |",
            "|---|---|---|---|",
        ]
        for asset in sorted(by_domain[domain], key=lambda a: a.id):
            path = _relative_path(repo_root, asset.path)
            lines.append(
                f"| `{asset.id}` | {asset.name} | {asset.type} | `{path}` |"
            )

    total_assets = sum(len(assets) for assets in by_domain.values())
    lines += [
        "",
        "## Totals",
        "",
        "```text",
        f"Domains: {len(domains)}",
        f"Total assets: {total_assets}",
        "```",
        "",
        "## Final Principle",
        "",
        "> Domain reports show how Aegis OS assets are distributed across "
        "functional areas.",
    ]
    return "\n".join(lines) + "\n"


def generate_release_report(resolver: AssetResolver) -> str:
    """Build RELEASE_REPORT.md content.

    The releases registry uses a different schema than the rest of the
    registry (top-level 'releases:' key, fields like version/release_type/
    maturity instead of type/domain). RegistryLoader still normalizes each
    entry into an Asset (its 'releases' key is one of the preferred_keys
    it extracts), it just leaves release-specific fields in Asset.metadata
    since they have no dedicated Asset attribute. This reads them from
    there rather than assuming an Asset.type that was never set.
    """

    releases = sorted(
        (asset for asset in resolver.assets if asset.id.startswith("release.")),
        key=lambda asset: str(asset.metadata.get("version") or asset.id),
    )

    lines: list[str] = [
        "# Aegis OS - Release Report",
        "",
        "Generated by:",
        "",
        "```text",
        "aegis report generate release-report",
        "```",
        "",
        "## Releases",
        "",
        "| ID | Name | Version | Status | Maturity |",
        "|---|---|---|---|---|",
    ]

    for release in releases:
        version = release.metadata.get("version", "")
        status = release.metadata.get("status", "")
        maturity = release.metadata.get("maturity", "")
        lines.append(
            f"| `{release.id}` | {release.name} | {version} | "
            f"{status} | {maturity} |"
        )

    lines += ["", "## Details"]

    for release in releases:
        version = release.metadata.get("version", "")
        status = release.metadata.get("status", "")
        maturity = release.metadata.get("maturity", "")
        summary = release.metadata.get("summary", "")
        lines += [
            "",
            f"### {version} - {release.name}",
            "",
            "```text",
            f"ID: {release.id}",
            f"Status: {status}",
            f"Maturity: {maturity}",
            "```",
            "",
            str(summary),
        ]

    lines += [
        "",
        "## Totals",
        "",
        "```text",
        f"Total releases: {len(releases)}",
        "```",
        "",
        "## Final Principle",
        "",
        "> Release reports make Aegis OS milestone progress visible and auditable.",
    ]
    return "\n".join(lines) + "\n"


REPORT_GENERATORS = ("registry-summary", "asset-map", "domain-report", "release-report")


def generate_report(
    name: str,
    resolver: AssetResolver,
    repo_root: Path,
    registry_files: list[Path],
) -> GeneratedReport:
    """Generate a single named report and write it to reports/registry/."""

    output_dir = repo_root / REPORTS_SUBDIR
    output_dir.mkdir(parents=True, exist_ok=True)

    if name == "registry-summary":
        content = generate_registry_summary(resolver, repo_root, registry_files)
        filename = "REGISTRY_SUMMARY.md"
    elif name == "asset-map":
        content = generate_asset_map(resolver, repo_root)
        filename = "ASSET_MAP.md"
    elif name == "domain-report":
        content = generate_domain_report(resolver, repo_root)
        filename = "DOMAIN_REPORT.md"
    elif name == "release-report":
        content = generate_release_report(resolver)
        filename = "RELEASE_REPORT.md"
    else:
        raise ValueError(f"Unknown report: {name}")

    output_path = output_dir / filename
    output_path.write_text(content, encoding="utf-8")
    return GeneratedReport(name=name, path=output_path)


def generate_all_reports(
    resolver: AssetResolver,
    repo_root: Path,
    registry_files: list[Path],
) -> list[GeneratedReport]:
    """Generate every registry report in a deterministic order."""

    return [
        generate_report(name, resolver, repo_root, registry_files)
        for name in REPORT_GENERATORS
    ]
