<#
.SYNOPSIS
Generates the Aegis OS registry summary report.

.DESCRIPTION
Scans registry YAML files and creates a human-readable summary report.

.USAGE
powershell -ExecutionPolicy Bypass -File scripts\reports\generate-registry-summary.ps1
#>

$ErrorActionPreference = "Stop"

Write-Host "Aegis OS - Registry Summary Report" -ForegroundColor Cyan

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptRoot "..\..")

Set-Location $repoRoot

$registryRoot = "registry"
$outputDir = "reports\registry"
$outputFile = Join-Path $outputDir "REGISTRY_SUMMARY.md"

if (-not (Test-Path $registryRoot)) {
    Write-Error "Registry folder not found: $registryRoot"
    exit 1
}

if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$yamlFiles = @(
    Get-ChildItem -Path $registryRoot -Recurse -File |
    Where-Object {
        $_.Extension -eq ".yaml" -or $_.Extension -eq ".yml"
    }
)

if ($yamlFiles.Count -eq 0) {
    Write-Error "No registry YAML files found."
    exit 1
}

$lines = @()
$lines += "# Aegis OS - Registry Summary"
$lines += ""
$lines += "Generated by:"
$lines += ""
$lines += '```text'
$lines += "scripts/reports/generate-registry-summary.ps1"
$lines += '```'
$lines += ""
$lines += "## Summary"
$lines += ""
$lines += "| Registry File | Entry Count |"
$lines += "|---|---:|"

$totalEntries = 0

foreach ($file in ($yamlFiles | Sort-Object FullName)) {
    $contentLines = Get-Content $file.FullName

    $entryCount = 0

    foreach ($line in $contentLines) {
        if ($line -match "^\s{2}-\s*id:\s*(.+)\s*$") {
            $entryCount++
        }
    }

    $relativePath = Resolve-Path $file.FullName -Relative
    $relativePath = $relativePath -replace "^\.\\" , ""

    $lines += "| `$relativePath` | $entryCount |"

    $totalEntries += $entryCount
}

$lines += ""
$lines += "## Totals"
$lines += ""
$lines += '```text'
$lines += "Registry files: $($yamlFiles.Count)"
$lines += "Total entries: $totalEntries"
$lines += '```'
$lines += ""
$lines += "## Final Principle"
$lines += ""
$lines += "> Registry summaries make the Aegis OS asset catalog easier to inspect."

Set-Content -Path $outputFile -Value $lines -Encoding UTF8

Write-Host "OK  Generated $outputFile" -ForegroundColor Green
exit 0