<#
.SYNOPSIS
Generates the Aegis OS domain report.

.DESCRIPTION
Scans registry YAML files and groups registered assets by domain.

.USAGE
pwsh -ExecutionPolicy Bypass -File scripts\reports\generate-domain-report.ps1
#>

$ErrorActionPreference = "Stop"

Write-Host "Aegis OS - Domain Report" -ForegroundColor Cyan

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptRoot "..\..")

Set-Location $repoRoot

$registryRoot = "registry"
$outputDir = "reports\registry"
$outputFile = Join-Path $outputDir "DOMAIN_REPORT.md"

if (-not (Test-Path $registryRoot)) {
    Write-Error "Registry folder not found: $registryRoot"
    exit 1
}

if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$yamlFiles = @(
    Get-ChildItem -Path $registryRoot -Recurse -File |
    Where-Object {
        $_.Extension -eq ".yaml" -or $_.Extension -eq ".yml"
    }
)

if ($yamlFiles.Count -eq 0) {
    Write-Error "No registry YAML files found."
    exit 1
}

$assets = [System.Collections.Generic.List[object]]::new()

foreach ($file in ($yamlFiles | Sort-Object FullName)) {
    $lines = Get-Content $file.FullName

    $currentId = ""
    $currentName = ""
    $currentType = ""
    $currentDomain = ""
    $currentPath = ""
    $insideEntry = $false

    foreach ($line in $lines) {
        if ($line -match '^\s{2}-\s*id:\s*(.+)\s*$') {
            if ($insideEntry -and -not [string]::IsNullOrWhiteSpace($currentId)) {
                $assets.Add([PSCustomObject]@{
                    Id     = $currentId
                    Name   = $currentName
                    Type   = $currentType
                    Domain = $currentDomain
                    Path   = $currentPath
                })
            }

            $insideEntry = $true
            $currentId = $Matches[1].Trim().Trim('"').Trim("'")
            $currentName = ""
            $currentType = ""
            $currentDomain = ""
            $currentPath = ""
            continue
        }

        if ($insideEntry -and $line -match '^\s*name:\s*(.+)\s*$') {
            $currentName = $Matches[1].Trim().Trim('"').Trim("'")
            continue
        }

        if ($insideEntry -and $line -match '^\s*type:\s*(.+)\s*$') {
            $currentType = $Matches[1].Trim().Trim('"').Trim("'")
            continue
        }

        if ($insideEntry -and $line -match '^\s*domain:\s*(.+)\s*$') {
            $currentDomain = $Matches[1].Trim().Trim('"').Trim("'")
            continue
        }

        if ($insideEntry -and $line -match '^\s*path:\s*(.+)\s*$') {
            $currentPath = $Matches[1].Trim().Trim('"').Trim("'")
            continue
        }
    }

    if ($insideEntry -and -not [string]::IsNullOrWhiteSpace($currentId)) {
        $assets.Add([PSCustomObject]@{
            Id     = $currentId
            Name   = $currentName
            Type   = $currentType
            Domain = $currentDomain
            Path   = $currentPath
        })
    }
}

$domains = $assets |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_.Domain) } |
    Group-Object Domain |
    Sort-Object Name

$reportLines = [System.Collections.Generic.List[string]]::new()
$reportLines.Add("# Aegis OS - Domain Report")
$reportLines.Add("")
$reportLines.Add("Generated by:")
$reportLines.Add("")
$reportLines.Add('```text')
$reportLines.Add("scripts/reports/generate-domain-report.ps1")
$reportLines.Add('```')
$reportLines.Add("")
$reportLines.Add("## Summary")
$reportLines.Add("")
$reportLines.Add("| Domain | Asset Count |")
$reportLines.Add("|---|---:|")

foreach ($domain in $domains) {
    $reportLines.Add("| $($domain.Name) | $($domain.Count) |")
}

$reportLines.Add("")
$reportLines.Add("## Assets by Domain")

foreach ($domain in $domains) {
    $reportLines.Add("")
    $reportLines.Add("### $($domain.Name)")
    $reportLines.Add("")
    $reportLines.Add("| ID | Name | Type | Path |")
    $reportLines.Add("|---|---|---|---|")

    foreach ($asset in ($domain.Group | Sort-Object Id)) {
        $reportLines.Add("| `$($asset.Id)` | $($asset.Name) | $($asset.Type) | `$($asset.Path)` |")
    }
}

$reportLines.Add("")
$reportLines.Add("## Totals")
$reportLines.Add("")
$reportLines.Add('```text')
$reportLines.Add("Domains: $($domains.Count)")
$reportLines.Add("Total assets: $($assets.Count)")
$reportLines.Add('```')
$reportLines.Add("")
$reportLines.Add("## Final Principle")
$reportLines.Add("")
$reportLines.Add("> Domain reports show how Aegis OS assets are distributed across functional areas.")

Set-Content -Path $outputFile -Value $reportLines -Encoding UTF8

Write-Host "OK  Generated $outputFile" -ForegroundColor Green
exit 0