<#
.SYNOPSIS
Generates the Aegis OS registry summary report.

.DESCRIPTION
Scans registry YAML files and creates a human-readable summary report.

.USAGE
pwsh -ExecutionPolicy Bypass -File scripts\reports\generate-registry-summary.ps1
#>

$ErrorActionPreference = "Stop"

Write-Host "Aegis OS - Registry Summary Report" -ForegroundColor Cyan

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptRoot "..\..")

Set-Location $repoRoot

$registryRoot = "registry"
$outputDir = "reports\registry"
$outputFile = Join-Path $outputDir "REGISTRY_SUMMARY.md"

if (-not (Test-Path $registryRoot)) {
    Write-Error "Registry folder not found: $registryRoot"
    exit 1
}

if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$yamlFiles = @(
    Get-ChildItem -Path $registryRoot -Recurse -File |
    Where-Object {
        $_.Extension -eq ".yaml" -or $_.Extension -eq ".yml"
    }
)

if ($yamlFiles.Count -eq 0) {
    Write-Error "No registry YAML files found."
    exit 1
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Aegis OS - Registry Summary")
$lines.Add("")
$lines.Add("Generated by:")
$lines.Add("")
$lines.Add('```text')
$lines.Add("scripts/reports/generate-registry-summary.ps1")
$lines.Add('```')
$lines.Add("")
$lines.Add("## Summary")
$lines.Add("")
$lines.Add("| Registry File | Entry Count |")
$lines.Add("|---|---:|")

$totalEntries = 0

foreach ($file in ($yamlFiles | Sort-Object FullName)) {
    $contentLines = Get-Content $file.FullName

    $entryCount = 0

    foreach ($line in $contentLines) {
        if ($line -match "^\s{2}-\s*id:\s*(.+)\s*$") {
            $entryCount++
        }
    }

    $relativePath = Resolve-Path $file.FullName -Relative
    $relativePath = $relativePath -replace "^\.\\" , ""

    $lines.Add("| `$relativePath` | $entryCount |")

    $totalEntries += $entryCount
}

$lines.Add("")
$lines.Add("## Totals")
$lines.Add("")
$lines.Add('```text')
$lines.Add("Registry files: $($yamlFiles.Count)")
$lines.Add("Total entries: $totalEntries")
$lines.Add('```')
$lines.Add("")
$lines.Add("## Final Principle")
$lines.Add("")
$lines.Add("> Registry summaries make the Aegis OS asset catalog easier to inspect.")

Set-Content -Path $outputFile -Value $lines -Encoding UTF8

Write-Host "OK  Generated $outputFile" -ForegroundColor Green
exit 0