<#
.SYNOPSIS
Generates the Aegis OS release report.

.DESCRIPTION
Scans the releases registry and creates a human-readable release report.

.USAGE
pwsh -ExecutionPolicy Bypass -File scripts\reports\generate-release-report.ps1
#>

$ErrorActionPreference = "Stop"

Write-Host "Aegis OS - Release Report" -ForegroundColor Cyan

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptRoot "..\..")

Set-Location $repoRoot

$registryPath = "registry\releases\releases.registry.yaml"
$outputDir = "reports\registry"
$outputFile = Join-Path $outputDir "RELEASE_REPORT.md"

if (-not (Test-Path $registryPath)) {
    Write-Error "Releases registry not found: $registryPath"
    exit 1
}

if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$lines = Get-Content $registryPath
$releases = [System.Collections.Generic.List[object]]::new()

$currentId = ""
$currentName = ""
$currentVersion = ""
$currentStatus = ""
$currentMaturity = ""
$currentSummary = ""
$insideEntry = $false

foreach ($line in $lines) {
    if ($line -match '^\s{2}-\s*id:\s*(release\..+)\s*$') {
        if ($insideEntry -and -not [string]::IsNullOrWhiteSpace($currentId)) {
            $releases.Add([PSCustomObject]@{
                Id       = $currentId
                Name     = $currentName
                Version  = $currentVersion
                Status   = $currentStatus
                Maturity = $currentMaturity
                Summary  = $currentSummary
            })
        }

        $insideEntry = $true
        $currentId = $Matches[1].Trim().Trim('"').Trim("'")
        $currentName = ""
        $currentVersion = ""
        $currentStatus = ""
        $currentMaturity = ""
        $currentSummary = ""
        continue
    }

    if ($insideEntry -and $line -match '^\s*name:\s*(.+)\s*$') {
        $currentName = $Matches[1].Trim().Trim('"').Trim("'")
        continue
    }

    if ($insideEntry -and $line -match '^\s*version:\s*(.+)\s*$') {
        $currentVersion = $Matches[1].Trim().Trim('"').Trim("'")
        continue
    }

    if ($insideEntry -and $line -match '^\s*status:\s*(.+)\s*$') {
        $currentStatus = $Matches[1].Trim().Trim('"').Trim("'")
        continue
    }

    if ($insideEntry -and $line -match '^\s*maturity:\s*(.+)\s*$') {
        $currentMaturity = $Matches[1].Trim().Trim('"').Trim("'")
        continue
    }

    if ($insideEntry -and $line -match '^\s*summary:\s*(.+)\s*$') {
        $currentSummary = $Matches[1].Trim().Trim('"').Trim("'")
        continue
    }
}

if ($insideEntry -and -not [string]::IsNullOrWhiteSpace($currentId)) {
    $releases.Add([PSCustomObject]@{
        Id       = $currentId
        Name     = $currentName
        Version  = $currentVersion
        Status   = $currentStatus
        Maturity = $currentMaturity
        Summary  = $currentSummary
    })
}

$reportLines = [System.Collections.Generic.List[string]]::new()
$reportLines.Add("# Aegis OS - Release Report")
$reportLines.Add("")
$reportLines.Add("Generated by:")
$reportLines.Add("")
$reportLines.Add('```text')
$reportLines.Add("scripts/reports/generate-release-report.ps1")
$reportLines.Add('```')
$reportLines.Add("")
$reportLines.Add("## Releases")
$reportLines.Add("")
$reportLines.Add("| ID | Name | Version | Status | Maturity |")
$reportLines.Add("|---|---|---|---|---|")

foreach ($release in ($releases | Sort-Object Version)) {
    $reportLines.Add("| `$($release.Id)` | $($release.Name) | $($release.Version) | $($release.Status) | $($release.Maturity) |")
}

$reportLines.Add("")
$reportLines.Add("## Details")

foreach ($release in ($releases | Sort-Object Version)) {
    $reportLines.Add("")
    $reportLines.Add("### $($release.Version) - $($release.Name)")
    $reportLines.Add("")
    $reportLines.Add('```text')
    $reportLines.Add("ID: $($release.Id)")
    $reportLines.Add("Status: $($release.Status)")
    $reportLines.Add("Maturity: $($release.Maturity)")
    $reportLines.Add('```')
    $reportLines.Add("")
    $reportLines.Add($release.Summary)
}

$reportLines.Add("")
$reportLines.Add("## Totals")
$reportLines.Add("")
$reportLines.Add('```text')
$reportLines.Add("Total releases: $($releases.Count)")
$reportLines.Add('```')
$reportLines.Add("")
$reportLines.Add("## Final Principle")
$reportLines.Add("")
$reportLines.Add("> Release reports make Aegis OS milestone progress visible and auditable.")

Set-Content -Path $outputFile -Value $reportLines -Encoding UTF8

Write-Host "OK  Generated $outputFile" -ForegroundColor Green
exit 0