<#
.SYNOPSIS
Generates the Aegis OS asset map report.

.DESCRIPTION
Scans registry YAML files and creates a human-readable asset map.

.USAGE
powershell -ExecutionPolicy Bypass -File scripts\reports\generate-asset-map.ps1
#>

$ErrorActionPreference = "Stop"

Write-Host "Aegis OS - Asset Map Report" -ForegroundColor Cyan

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptRoot "..\..")

Set-Location $repoRoot

$registryRoot = "registry"
$outputDir = "reports\registry"
$outputFile = Join-Path $outputDir "ASSET_MAP.md"

if (-not (Test-Path $registryRoot)) {
    Write-Error "Registry folder not found: $registryRoot"
    exit 1
}

if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$yamlFiles = @(
    Get-ChildItem -Path $registryRoot -Recurse -File |
    Where-Object {
        $_.Extension -eq ".yaml" -or $_.Extension -eq ".yml"
    }
)

if ($yamlFiles.Count -eq 0) {
    Write-Error "No registry YAML files found."
    exit 1
}

$assets = @()

foreach ($file in ($yamlFiles | Sort-Object FullName)) {
    $lines = Get-Content $file.FullName

    $currentId = ""
    $currentName = ""
    $currentType = ""
    $currentDomain = ""
    $currentPath = ""
    $insideEntry = $false

    foreach ($line in $lines) {
        if ($line -match "^\s{2}-\s*id:\s*(.+)\s*$") {
            if ($insideEntry -and -not [string]::IsNullOrWhiteSpace($currentId)) {
                $assets += [PSCustomObject]@{
                    Id = $currentId
                    Name = $currentName
                    Type = $currentType
                    Domain = $currentDomain
                    Path = $currentPath
                    Source = (Resolve-Path $file.FullName -Relative)
                }
            }

            $insideEntry = $true
            $currentId = $Matches[1].Trim().Trim('"').Trim("'")
            $currentName = ""
            $currentType = ""
            $currentDomain = ""
            $currentPath = ""
            continue
        }

        if ($insideEntry -and $line -match "^\s*name:\s*(.+)\s*$") {
            $currentName = $Matches[1].Trim().Trim('"').Trim("'")
            continue
        }

        if ($insideEntry -and $line -match "^\s*type:\s*(.+)\s*$") {
            $currentType = $Matches[1].Trim().Trim('"').Trim("'")
            continue
        }

        if ($insideEntry -and $line -match "^\s*domain:\s*(.+)\s*$") {
            $currentDomain = $Matches[1].Trim().Trim('"').Trim("'")
            continue
        }

        if ($insideEntry -and $line -match "^\s*path:\s*(.+)\s*$") {
            $currentPath = $Matches[1].Trim().Trim('"').Trim("'")
            continue
        }
    }

    if ($insideEntry -and -not [string]::IsNullOrWhiteSpace($currentId)) {
        $assets += [PSCustomObject]@{
            Id = $currentId
            Name = $currentName
            Type = $currentType
            Domain = $currentDomain
            Path = $currentPath
            Source = (Resolve-Path $file.FullName -Relative)
        }
    }
}

$reportLines = @()
$reportLines += "# Aegis OS - Asset Map"
$reportLines += ""
$reportLines += "Generated by:"
$reportLines += ""
$reportLines += '```text'
$reportLines += "scripts/reports/generate-asset-map.ps1"
$reportLines += '```'
$reportLines += ""
$reportLines += "## Assets"
$reportLines += ""
$reportLines += "| ID | Name | Type | Domain | Path |"
$reportLines += "|---|---|---|---|---|"

foreach ($asset in ($assets | Sort-Object Domain, Id)) {
    $id = $asset.Id
    $name = $asset.Name
    $type = $asset.Type
    $domain = $asset.Domain
    $path = $asset.Path

    $reportLines += "| `$id` | $name | $type | $domain | `$path` |"
}

$reportLines += ""
$reportLines += "## Totals"
$reportLines += ""
$reportLines += '```text'
$reportLines += "Total assets: $($assets.Count)"
$reportLines += '```'
$reportLines += ""
$reportLines += "## Final Principle"
$reportLines += ""
$reportLines += "> Asset maps make registered Aegis OS assets easier to inspect and navigate."

Set-Content -Path $outputFile -Value $reportLines -Encoding UTF8

Write-Host "OK  Generated $outputFile" -ForegroundColor Green
exit 0